spring:
  application:
    name: leafy
  profiles:
    active: local
    include: oauth, secret

  codec:
    max-in-memory-size: 5MB

kakao:
  admin-key: ${KAKAO_ADMIN_KEY}

app:
  user:
    withdrawal-recovery-days: 30