spring.application.name=leafy

spring.profiles.include=oauth, secret

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/leafy?serverTimezone=Asia/Seoul
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}

spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Redis ??
spring.data.redis.host=localhost
spring.data.redis.port=6379

# WebClient ?? ??
spring.codec.max-in-memory-size=5MB
spring.batch.job.enabled=true